language: php
php:
  - "5.6"
  - "7.0"
  - "hhvm"

before_script:
  - composer self-update
  - composer install

script: 
  - bin/phpunit --coverage-text

matrix:
     allow_failures:
         - php: "hhvm"
